version: '3'
services:
  xmonad:
    container_name: server
    image: youngker/xmonad:1.3
    ports:
      - '3389:3389'
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
