version: '3.7'
services:
  xmonad:
    build: .
    container_name: server
    image: youngker/xmonad:1.7
    shm_size: '2gb'
    hostname: docker-xmonad
    ports:
      - '3389:3389'
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
